# Site settings
title: Felix's blog
email: longbiaochen@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  The world's mine oyster.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://longbiaochen.com" # the base hostname & protocol for your site
twitter_username: longbiaochen
github_username:  longbiaochen

# Build settings
markdown: kramdown
