# Site settings
title: Welcome
email: longbiaochen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" 
url: "http://longbiaochen.com"
twitter_username: longbiaochen
github_username:  longbiaochen

# Build settings
markdown: kramdown

